### ISSUE TITLE
Dark mode hover variants

### ISSUE THREAD

**Issue by AlleyShairu** [ChanceArthur/tailwindcss-dark-mode#1]
I am using Tailwind beta version (1.0.0-beta.5), and I am not sure if this is done willingly or its a bug?

Example:
**Not possible `hover:dark:bg-gray-300`**
**Possible `sm:dark:bg-gray-300 `**

I can't understand why it doesn't generate CSS for hover variants, but generates for responsive variants.

Thank you for creating this plugin.

**Comment by ChanceArthur** [comment]
@AlleyShairu

Somehow I hadn't run into this issue yet in my own projects. Thanks for bringing it up. [I contacted Adam about it.](https://twitter.com/adamwathan/status/1123677086382796801) It turns out that Tailwind can only stack responsive variants.

Later today I'll add new variants such as `dark-hover`, and I'll update the README.

**Comment by ChanceArthur** [comment]
I've published v1.0.3. Check out the README for the new variants.

Just a heads up: [Tailwind 1.0.0-beta.6 and above have added a couple utilities, and removed one.](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.0.0-beta.6) Whether or not these are breaking changes will depend on your config file.

**Comment by jlarmstrongiv** [comment]
Ahh, thanks for the details!  I was watching the [screencasts](https://youtu.be/olyRu5R1EZ4?t=313) today and saw `md:hover:bg-green-400`.  Good to know it only works with responsive variants 👍
