### ISSUE TITLE
Feature : .mode-dark selector should be customizable

### ISSUE THREAD

**Issue by tbetous** [ChanceArthur/tailwindcss-dark-mode#11]
I think it would be nice if we have the ability to customize .mode-dark selector. For instance I have already implemented my own system to switch into dark or light theme by inserting data-theme="dark" into <body> tag.

I would like to use the selector [data-theme="dark"]

A great way to use this should be to use `theme` property into `tailwind.config.js` file. It's a quick work I'll make a PR.

By the way, thanks for your amazing work ! ;)

**Comment by hawezo** [comment]
Since your PR is not getting merged, I'll allow myself to introduce you to [`tailwindcss-theming`](https://github.com/hawezo/tailwindcss-theming), which supports [multiple strategies](https://github.com/hawezo/tailwindcss-theming/blob/master/docs/configuration.md#strategies) (`data-theme` included).

**Comment by ChanceArthur** [comment]
I'm planning to merge this soon. I've just been catching up after vacation. Thanks for your work!

**Comment by tbetous** [comment]
Thanks a lot !
