### ISSUE TITLE
prefers-dark.js Error

### ISSUE THREAD

**Issue by Mozart409** [ChanceArthur/tailwindcss-dark-mode#15]
Hi,
every time I try use the prefers-dark.js I get an error ReferenceError: document is not defined. No matter what framework I use. Can you help?

**Comment by ChanceArthur** [comment]
Where is your script tag located?

**Comment by Mozart409** [comment]
When using gatsbyjs in my layout component
when using nextjs in my _app.js component

**Comment by ChanceArthur** [comment]
I don't use React, so I can't be of much help. The included script is vanilla Javascript. It's saying it can't find the <html> tag.
Since you're using React, I'd imagine that there should be a better React-based solution out there somewhere that can add a class to the <html> tag based on the user's theme preferences.

**Comment by Mozart409** [comment]
ok thanks. :)
